team1app/blog/urls.py
from rest_framework import routers
#from .views import UserViewSet, EntryViewSet


router = routers.DefaultRouter()


"""
router.register(r'users',UserViewSet)
router.register(r'entries',EntryViewSet)
"""

team1app/students/urls.py
from django.urls import path, re_path
from . import views,test

from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static


# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'students'

urlpatterns = [

    path('', views.home, name = 'home'),
    path('home/<int:class_id>/', views.class_page, name = "class_page"), 
    path('home/task/', views.task, name = 'task'),
    path('home/propose/', views.propose, name = 'propose'),
    path('home/tag/', views.tag, name = 'tag'),

    path('home/chat/<int:id>/', views.room, name = 'room'),
    path('home/chat/', views.chat, name = 'chat'),
    path('home/chat/create/', views.chat_create, name = 'chat_create'),

]

team1app/team1app/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog.urls import router as blog_router
from django.urls import path, include
from teachers.views import home as tehome
from students.views import home as sthome
from blog import web_views_private as priv




urlpatterns=[
    path(r'admin/', admin.site.urls),
    path(r'api/', include(blog_router.urls)),
    #blog
    path('home/',priv.home,name='home'),
    path(r'', include('blog.web_urls')),

    path(r'accounts/',include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('student/',include('students.urls')),
    path('teacher/',include('teachers.urls',namespace="teacher")),
    path('teacher/home/',tehome,name='tehome'),
    path('student/home/',sthome,name='sthome'),
    
]

team1app/blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
import re

"""
class User(models.Model):
    name = models.CharField(max_length=32)
    mail = models.EmailField()
    def __repr__(self):
        # 主キーとnameを表示させて見やすくする
        # ex) 1: Alice
        return "{}: {}".format(self.pk, self.name)

    __str__ = __repr__  # __str__にも同じ関数を適用


class Entry(models.Model):
    STATUS_DRAFT = "draft"
    STATUS_PUBLIC = "public"
    STATUS_SET = (
            (STATUS_DRAFT, "下書き"),
            (STATUS_PUBLIC, "公開中"),
    )
    title = models.CharField(max_length=128)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=STATUS_SET, default=STATUS_DRAFT, max_length=8)
    author = models.ForeignKey(User, related_name='entries', on_delete=models.CASCADE)
"""
#教師
class Teachers(models.Model):
    name = models.CharField(max_length=32)
    person = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=None)
    use_base = models.IntegerField(default=None,null=True,blank=True)

    def getQuestions(self):
        result = None
        if(Question.objects.filter(toTe = self).exists):
            result = Question.objects.filter(toTe = self)
        return result

#生徒
class Students(models.Model):
    name = models.CharField(max_length=32)
    person = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=None)
    use_base = models.IntegerField(default=None,null=True,blank = True)
    
    def getQuestions(self):
        result = None
        if(Question.objects.filter(fromSt = self).exists):
            result = Question.objects.filter(fromSt = self)
        return result

    def getHomework(self):
        return self.studenttasks_set.all()

    def getClassHomework(self,Class):
        result = []
        for homework in self.studenttasks_set.all():
            if(homework.task.all()[0].tarclass == Class):
                result.append(homework)
        return result

    def getMyClassHomework(self):
        result = []
        if(Classes.objects.filter(students = self).exists()):
            cs = Classes.objects.filter(students = self)
            for c in cs:
                data = {"class":c,"homeworks":self.getClassHomework(c)}
                result.append(data)

        return result

    
    def getHomeworkT(self,teacher):
        hws = []
        for hw in self.studenttasks_set.all():
            for t in hw.task.all():
                for a in t.auther.all():
                    if(a == teacher):
                        hws.append(hw)
                        break
        return hws

#学校    
class Base(models.Model):
    base_name = models.CharField(max_length=128)
    #先生用
    password = models.CharField(max_length=32,default="0000")
    #生徒用
    password2 = models.CharField(max_length=32,default="1111")
    #管理者
    administrator = models.ManyToManyField(settings.AUTH_USER_MODEL)
    #在籍する教師
    teachers = models.ManyToManyField(Teachers)
    #在籍する生徒
    students = models.ManyToManyField(Students,blank=True)

#クラス関係

#クラス
class Classes(models.Model):
    #クラスの名前
    class_name=models.CharField(max_length=32)
    #所属するbase
    base = models.ForeignKey(Base,on_delete=models.CASCADE)
    #クラスのパスワード
    password = models.CharField(max_length=32,default=0000)
    #在籍する教師
    teachers = models.ManyToManyField(Teachers)
    #在籍する生徒
    students = models.ManyToManyField(Students,blank=True)

#タグ
class Tags(models.Model):
    #タグの名前
    tag = models.CharField(max_length=32)
    #タグのあるクラス
    tarclass = models.ForeignKey(Classes,on_delete=models.CASCADE)

#宿題
class Tasks(models.Model):
    #宿題の名前
    name = models.CharField(max_length=32)
    #宿題の内容
    contents = models.TextField()
    #作った人
    auther = models.ManyToManyField(Teachers)
    #宿題につけられたタグ
    tag = models.ManyToManyField(Tags,blank=True)
    #タグが置かれたクラス
    tarclass = models.ForeignKey(Classes,on_delete=models.CASCADE)
    #作られた日付
    make = models.DateField(default=timezone.now)

#生徒に出された宿題
class StudentTasks(models.Model):
    #出された宿題
    task = models.ManyToManyField(Tasks)
    #期限
    limit = models.DateField()
    #終わったかどうか
    finish = models.BooleanField(default=False)
    #正解があるかどうか
    isResult = models.BooleanField(default=False, blank=True, null=True)
    #宿題の正誤
    result = models.BooleanField(default=False)
    #出された人
    person = models.ForeignKey(Students,on_delete=models.CASCADE)

    def getIsResult(self):
        if self.isResult == null:
            return True
        else:
            return self.isResult 

class Schedule(models.Model):
    person = models.ForeignKey(Teachers,on_delete=models.CASCADE)

    def add(self,week,start_h,start_m,end_h,end_m):
        data = None
        datas = self.getScheduleData()
        if(datas != None):
            if(datas[week] != None):
                for i in datas[week]['data']:
                    sh,sm = i.getStartInt()
                    eh,em = i.getEndInt()

                    if(start_h < sh or (start_h == sh and start_m < sm)):
                        if(end_h < sh or (end_h == sh and end_m < sm)):
                            continue

                        elif(start_h < sh or (start_h == sh and start_m < sm)):
                            i.start="{:0>2}:{:0>2}".format(str(start_h),str(start_m))
                            if(data != None):
                                data.delete()
                            data = i
                            data.save()
                            end_h = eh
                            end_m = em
                            continue

                        else:
                            i.start="{:0>2}:{:0>2}".format(str(start_h),str(start_m))
                            i.end="{:0>2}:{:0>2}".format(str(end_h),str(end_m))
                            if(data != None):
                                data.delete()
                            data = i
                            data.save()
                            continue

                    elif(start_h < eh or (start_h == eh and start_m <= sm)):
                        if(start_h < sh or (start_h == sh and start_m < sm)):
                            data = i
                            break

                        else:
                            i.end="{:0>2}:{:0>2}".format(str(end_h),str(end_m))
                            if(data != None):
                                data.delete()
                            data = i
                            data.save()
                            start_h = eh
                            start_m = em
                            continue

                    else:
                        continue
        if(data == None):
            data = ScheduleData.objects.create(schedule = self,start = "{:0>2}:{:0>2}".format(start_h,start_m),end = "{:0>2}:{:0>2}".format(end_h,end_m))
            data.save()
        
        return 0

    def getScheduleData(self):
        strweek = "月火水木金土日"
        lst = None
        if(ScheduleData.objects.filter(schedule = self).exists()):
            scheduledatas = ScheduleData.objects.filter(schedule = self)
            lst = []
            for i in range(7):
                if(scheduledatas.filter(week = i).exists()):
                    d = scheduledatas.filter(week = i)
                    data = {"data":d,"weekstr":strweek[i]}
                    lst.append(data)
                else:
                    lst.append(None)
        return lst


class ScheduleData(models.Model):
    schedule = models.ForeignKey(Schedule,on_delete=models.CASCADE)
    week = models.IntegerField(default=0)
    start = models.CharField(max_length=5)
    end = models.CharField(max_length=5)

    def getStartInt(self):
        match = re.match(r"(\d+):(\d+)",self.start)
        return int(match.group(1)),int(match.group(2))

    def getEndInt(self):
        match = re.match(r"(\d+):(\d+)",self.end)
        return int(match.group(1)),int(match.group(2))



class Question(models.Model):
    task = models.ForeignKey(Tasks, on_delete = models.CASCADE)
    title = models.CharField(max_length = 32)
    fromSt =  models.ForeignKey(Students,on_delete=models.CASCADE)
    toTe = models.ForeignKey(Teachers,on_delete=models.CASCADE)
    finalup = models.DateTimeField(default=timezone.now)

    #AppoTimeを追加:days(何日後),何時(h),何分(m)
    def addAppo(self,days,h,m):
        now = timezone.now
        if(days > 0):
            now = now + datetime.timedelta(days = days)
        appo = AppoTime.objects.create(question = self,day = now,time = "{:0>2}:{:0>2}".format(h,m))
        appo.save()
        self.finalup = timezone.now
    
    def deleteAppoAll(self):
        if(AppoTime.objects.filter(question = self).exists()):
            appos = AppoTime.objects.filter(question = self)
            for appo in appos:
                appo.delete()


    def addAccept(self,appo):
        ac = Accept.objects.create(question = self,day = appo.day,time = appo.time)
        ac.save()
        self.deleteAppoAll()
        self.finalup = timezone.now
        
    #コメントの追加|生徒用    
    def addCommentSt(self,comment):
        comment = Comment.objects.create(question = self,comment = comment,isStudent = True)
        comment.save()
        self.finalup = timezone.now

    #コメントの追加|教師用
    def addCommentT(self,comment):
        comment = Comment.objects.create(question = self,comment = comment,isStudent = False)
        comment.save()
        self.finalup = timezone.now

    def getAppo(self):
        if(AppoTime.objects.filter(question = self).exists()):
            return AppoTime.objects.filter(question = self)
        else:
            return None

    def getAccept(self):
        if(Accept.objects.filter(question = self).exists()):
            return Accept.objects.filter(question = self)
        else:
            return None

team1app/blog/views.py
"""
import django_filters
from rest_framework import viewsets, filters

from .models import User, Entry
from .serializer import UserSerializer, EntrySerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class EntryViewSet(viewsets.ModelViewSet):
    queryset = Entry.objects.all()
    serializer_class = EntrySerializer
    filter_fields = ('author', 'status')
"""

team1app/blog/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/base_teacher.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/form_teacher.css' %}">
    {% block css %} 
    
    {% endblock css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'form.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Caveat|Quicksand:400,700" rel="stylesheet">
    {% block title %}  {% endblock title %} 
  </head>
  <body class = "body">  
     
    <header class="base_header">
      <h1 class="headline head">
        <a>+NoteBook</a>
      </h1>
      <ul class="nav-list">
        <li class="nav-list-item">
          <a href="{% url 'home' %}" >Home</a>
        </li>
        <li class="nav-list-item"><a  href="{% url 'login' %}" >SignOut</a></li>
        <li class="nav-list-item">Topic</li>
      </ul>

      <p class = "headline" align="right">ユーザー名：{{ user.username }}</p>
    </header>        

   {% block header %}
   {% endblock header %}
   {% block content %}

   {% endblock content %}

    <!-- java html -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

team1app/blog/templates/base_room.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>room.htmlのCSS</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'student/room.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'student/base_student.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'student/form_student.css' %}">
    {% block css %} 
    {% endblock css %}
    {% block title %}  {% endblock title %} 
  </head>
  <body>  
    <div class="header">
      <li class = "headword_p">{{ one.toTe.name }}</li>
     <li class = "room_p"><a href="../" class="room_p_a">一覧へ戻る</a></li> 
    </div>
  <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
  <label for="openSidebarMenu" class="sidebarIconToggle" style="position: fixed;">
    <div class="spinner diagonal part-1"></div>
    <div class="spinner horizontal"></div>
    <div class="spinner diagonal part-2"></div>
  </label>
  <div id="sidebarMenu">
    <ul class="sidebarMenuInner">
      <a href="{% url 'students:task' %}"><li>課題 <span>かだい</span></li></a>
      <a href="{% url 'students:tag' %}"><li>タグ</li></a>
      <a href="{% url 'students:chat' %}"><li>チャット</li></a>
      <a href="{% url 'home' %}"><li>トップ</li></a>
      <li>設定  <span>せってい</span></li>

    </ul>
  </div>
  <div class = "padding"></div>

   {% block header %}
   {% endblock header %}
   
   {% block content %}

   {% endblock content %} 
  </body>
</html>

team1app/blog/templates/base_student copy.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'student/base_student.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'student/form_student.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    

    {% block css %} 
    
    {% endblock css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'form.css' %}">
   
    {% block title %}  {% endblock title %} 
    
    
  </head>
  <body>  
   
    <header class = "base_header">
      <h1 class = "notebook">
        +NoteBook
      </h1>

      <div id="nav-drawer">
        <input id="nav-input" type="checkbox" class="nav-unshown">
        <label id="nav-open" for="nav-input"><span></span></label>
        <label class="nav-unshown" id="nav-close" for="nav-input"></label>
        <div id="nav-content">
          <p><a href="{% url 'students:task' %}" class="btn btn-success">Task</a></p>
          <p><a href="{% url 'students:propose' %}" >Propose</a></p>
          <p><a href="{% url 'students:reserve' %}">Reserve</a></p>
          <p><a href="{% url 'students:tag' %}">Tag</a></p>
          <p><a href="{% url 'top' %}">Top</a></p>

        </div>

        <div class = "top">
        <a  href="{% url 'top' %}" >TOP</a>
        <a href="{% url 'login' %}" >SignOut</a>
        <p class = "nav-list-item" >ユーザー名：{{ user.username }}</p>
        </div>
      </div>   
    </header>        

   {% block header %}
   {% endblock header %}
   <div>
   {% block content %}

   {% endblock content %}
  

  <!-- Swiper JS -->
  <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

  <!-- Initialize Swiper -->
  <script>
		var swiper = new Swiper('.swiper-container', {
      slidesPerView: 3,
      spaceBetween: 30,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
    });
  </script>
   
  </body>
</html>

team1app/blog/templates/base_student.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'student/base_student.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'student/form_student.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    

    {% block css %} 
    
    {% endblock css %}
    
    
   
    {% block title %}  {% endblock title %} 
    
    
  </head>
  <body>  
    
  <div class="header"><h1 class = "headword">+notebook</h1></div>
  <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
  <label for="openSidebarMenu" class="sidebarIconToggle" style="position: fixed;">
    <div class="spinner diagonal part-1"></div>
    <div class="spinner horizontal"></div>
    <div class="spinner diagonal part-2"></div>
  </label>
  <div id="sidebarMenu">
    <ul class="sidebarMenuInner">
      <a href="{% url 'students:task' %}"><li>課題 <span>かだい</span></li></a>
      <a href="{% url 'students:tag' %}"><li>タグ</li></a>
      <a href="{% url 'students:chat' %}"><li>チャット</li></a>
      <a href="{% url 'home' %}"><li>トップ</li></a>
      <li>設定  <span>せってい</span></li>

    </ul>
  </div>
  <div class = "padding"></div>
  

  
      
   

   {% block header %}
   {% endblock header %}
   
   {% block content %}

   {% endblock content %}
  

  <!-- Swiper JS -->

  
   
  </body>
</html>