team1app/blog/urls.py
from rest_framework import routers
#from .views import UserViewSet, EntryViewSet


router = routers.DefaultRouter()


"""
router.register(r'users',UserViewSet)
router.register(r'entries',EntryViewSet)
"""

team1app/teachers/urls.py
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'teachers'

urlpatterns = [
    path('class/',views.edit_class,name='teclass'),
    path('create_class/',views.create_class,name='CreateClass'),
    path('class/<int:classid>/',views.class_content,name='ClassContent'),
    path('class/<int:classid>/task/create/',views.create_task,name='CreateTask'),
    path('class/<int:classid>/tasks/',views.TasksList,name='TasksList'),
    path('class/<int:classid>/task/<int:taskid>/',views.taskContent,name="taskContent"),
    path('class/<int:classid>/tags/',views.edit_tags),
    path('class/<int:classid>/st/<int:studentid>/',views.studentContents),

    path('schedule/',views.schedule),
    path('questions/',views.questions,name="questions"),
    path('questions/<int:id>/',views.question),
    
]

team1app/team1app/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog.urls import router as blog_router
from django.urls import path, include
from teachers.views import home as tehome
from students.views import home as sthome
from blog import web_views_private as priv




urlpatterns=[
    path(r'admin/', admin.site.urls),
    path(r'api/', include(blog_router.urls)),
    #blog
    path('home/',priv.home,name='home'),
    path(r'', include('blog.web_urls')),

    path(r'accounts/',include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('student/',include('students.urls')),
    path('teacher/',include('teachers.urls',namespace="teacher")),
    path('teacher/home/',tehome,name='tehome'),
    path('student/home/',sthome,name='sthome'),
    
]

team1app/teachers/models.py
from django.db import models

# Create your models here.

team1app/teachers/views.py
from django.shortcuts import render,redirect
from blog.web_views_private import check
from blog.models import * 
from teachers.tools import * 
from django.utils import timezone
import datetime



# Create your views here.
def home(request):
    _,num = check(request)
    if num == 1:
        return redirect('teacher:teclass')
    else:
        return redirect('home')

def edit_class(request):
    Me,num = check(request)
    if num != 1:
        return redirect('home')
    if request.method != 'POST':
        if (Me.classes_set.all()):
            classes=Me.classes_set.all()
            data = {"classes":classes,"all":False}
            return render(request,'teachers/class.html',data)
        return render(request,'teachers/class.html')
    elif request.POST["type"] == "my" :
        if (Me.classes_set.all()):
            classes=Me.classes_set.all()
            data = {"classes":classes,"all":False}
            return render(request,'teachers/class.html',data)
        return render(request,'teachers/class.html')
    elif request.POST["join"] !="":
        c = Classes.objects.filter(id = int(request.POST["join"]))
        if(c.filter(teachers=Me).exists()):
            result = "すでに参加済みのクラスです"
        else:   
            c[0].teachers.add(Me)
            c[0].save() 
            result = c[0].class_name+"に参加しました"
        base = Base.objects.get(id = Me.use_base)
        if (base.classes_set.all()):
            classes=base.classes_set.all()
            data = {"classes":classes,"all":True,"result":result}
            return render(request,'teachers/class.html',data)
    else:
        base = Base.objects.get(id = Me.use_base)
        if (base.classes_set.all()):
            classes=base.classes_set.all()
            data = {"classes":classes,"all":True}
            return render(request,'teachers/class.html',data)
    return render(request,'teachers/class.html')


def create_class(request):
    teacher,num = check(request)
    if num != 1:
        return redirect('home')
    elif request.method !="POST":
        return render(request,'teachers/CreateClass.html')
    else:
        base = Base.objects.get(id = teacher.use_base)
        if (base.classes_set.all()):
            classes=base.classes_set.all()
            for tarclass in classes:
                if(tarclass.class_name==request.POST["name"]):
                    result ="すでに存在するクラス名です。"
                    return render(request,'teachers/CreateClass.html',{"result":result})
        thisclass=Classes.objects.create(class_name=request.POST["name"],password = request.POST["password"],base=base)
        thisclass.teachers.add(teacher)
        thisclass.save()
        return redirect("/teacher/class/")

def class_content(request,classid):
    #教師以外はリダイレクト
    teacher,num = check(request)
    if num != 1:
        return redirect('home')
    #ユーザーが使用しているベースにクラスが属しているか確認
    have,thisclass=checkCL(teacher.use_base,classid)
    #クラスが属していた
    if have :
            #クラスに生徒がいる場合
            if (thisclass.students.all()!= None):
                sts = thisclass.students.all()
                data={"thisclass":thisclass,"sts":sts,"tags":tagsstate(thisclass,teacher)}
                return render(request,'teachers/Content.html',data)
            #クラスに生徒がいない場合
            else:
                data={"thisclass":thisclass}
                return render(request,'teachers/Content.html',data)
    #クラスが属していない
    else:
        return redirect("/teacher/class/")

def create_task(request,classid):
    #教師以外はリダイレクト
    teacher,num = check(request)
    if num != 1:
        return redirect('home')
    #ユーザーが使用しているベースにクラスが属しているか確認
    have,thisclass=checkCL(teacher.use_base,classid)
    #クラスが属していた
    if have :
        #メソッドがPOSTでなければタスク作成ページに移動    
        if request.method != "POST":
            return render(request,'teachers/TaskCreate.html')
        else:
            task=Tasks.objects.create(name=request.POST["name"],contents=request.POST["content"],tarclass=thisclass)
            task.auther.add(teacher)
            task.save()
            return redirect("/teacher/class/"+str(classid)+"/task/"+str(task.id)+"/")
    else:
        return redirect("/teacher/class/")



def TasksList(request,classid):
    #教師以外はリダイレクト
    teacher,num = check(request)
    if num != 1:
        return redirect('home')
    #ユーザーが使用しているベースにクラスが属しているか確認
    if(not Classes.objects.get(id=classid).teachers.filter(id=teacher.id).exists()):
        return redirect("/teacher/class/")
    have,thisclass=checkCL(teacher.use_base,classid)
    #クラスが属していた
    if have :
        #メソッドがPOSTでなければタスク作成ページに移動    
        if(thisclass.tasks_set.all().filter(auther = teacher).exists()):
            tasks=thisclass.tasks_set.all().filter(auther = teacher)
            data = {"tasks":tasks}
            return render(request,'teachers/TaskList.html',data)
        else:
            return render(request,'teachers/TaskList.html')
    else:
        return redirect("/teacher/class/")

def taskContent(request,classid,taskid):
    teacher,num = check(request)
    if num != 1:
        return redirect('home')
    #ユーザーが使用しているベースにクラスが属しているか確認
    if(not Classes.objects.get(id=classid).teachers.filter(id=teacher.id).exists()):
        return redirect("/teacher/class/")
    have,thisclass=checkCL(teacher.use_base,classid)
    #クラスが属していた
    if have :
        #メソッドがPOSTでなければタスク作成ページに移動
        if request.method == "POST":
            if request.POST["type"] == "students":
                if request.POST.getlist("students"):
                    studentsid=request.POST.getlist("students")
                    thistask = Tasks.objects.get(id = taskid)
                    day=int(request.POST["days"])
                    days=[datetime.timedelta(days=1),datetime.timedelta(days=2),datetime.timedelta(days=3),datetime.timedelta(days=4),datetime.timedelta(days=5),datetime.timedelta(days=6),datetime.timedelta(weeks=1),datetime.timedelta(weeks=2),datetime.timedelta(weeks=4)]
                    for studentid in studentsid :
                        student = Students.objects.get(id=studentid)
                        homework=StudentTasks.objects.create(person=student,limit=timezone.now()+days[day])
                        homework.task.add(thistask)
                        homework.save()
                    return redirect("/teacher/class/")
            if request.POST["type"] == "change":
                if(thisclass.tasks_set.all().filter(auther = teacher).exists()):
                    tasks=thisclass.tasks_set.all().filter(auther = teacher)
                    for task in tasks:
                        if(task.id==taskid):
                            task.name=request.POST["name"]
                            task.contents=request.POST["content"]
                            task.save()

            if request.POST["type"] == "addtags":
                tasks=thisclass.tasks_set.all().filter(auther = teacher)
                for task in tasks:
                    if(task.id==taskid):
                        if(task.tag.all().exists()):
                            nowtags = task.tag.all()
                            for tagid in request.POST.getlist("tags"):
                                if(nowtags.filter(id=int(tagid)).exists()):
                                    alert = "aleady exists"
                                    print(alert)
                                else:
                                    task.tag.add(Tags.objects.get(id = int(tagid)))
                                    task.save()
                        else:
                            for tagid in request.POST.getlist("tags"):
                                task.tag.add(Tags.objects.get(id = int(tagid)))
                                task.save()
            if request.POST["type"] == "delete":
                tasks=thisclass.tasks_set.all().filter(auther = teacher)
                for task in tasks:
                    if(task.id==taskid):
                        tagids=request.POST.getlist("tags")
                        for tagid in tagids :
                            tag = Tags.objects.get(id = int(tagid))
                            task.tag.remove(tag)
                        task.save()
        if(thisclass.tasks_set.all().filter(auther = teacher).exists()):
            tasks=thisclass.tasks_set.all().filter(auther = teacher)
            for task in tasks:
                if(task.id==taskid):
                    sts = thisclass.students.all()
                    thistags = None
                    tags = None
                    if (task.tag.all().exists()):
                        thistags = task.tag.all()
                    if(Tags.objects.filter(tarclass = thisclass).exists()):
                        tags = Tags.objects.filter(tarclass = thisclass)
                        data = {"tags":tags}
                    data={"task":task,"students":sts,"tags":tags,"thistags":thistags}
                    return render(request,'teachers/TaskContent.html',data)
        else:
            return redirect("/teacher/class/")
    else:
        return redirect("/teacher/class/")

def edit_tags(request,classid):
    teacher,num = check(request)
    if num != 1:
        return redirect('home')
    have,thisclass=checkCL(teacher.use_base,classid)
    if have :   
        if request.method != "POST":
            data = {}
            if(Tags.objects.filter(tarclass = thisclass).exists()):
                tags = Tags.objects.filter(tarclass = thisclass)
                data = {"tags":tags}
            return render(request,'teachers/tagsEdit.html',data)
        else:
            if request.method == "POST":
                alert = None
                tags = None
                if request.POST["type"] == "delete":
                    tagids=request.POST.getlist("tags")
                    for tagid in tagids :
                        tag = Tags.objects.get(id = int(tagid))
                        tag.delete()
                if request.POST["type"] == "add":

team1app/teachers/templates/teachers/Content.html
{% extends 'base_teacher.html' %}

{% load static %}
{% block css %} 
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/class_teacher.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/graph.css' %}">
{% endblock css %}

{% block title %}
<title>Document</title>
{% endblock title %}



{% block content %}
<div class = "container">
    <div class ="Contentstitle">
        <span>クラス詳細〜{{thisclass.class_name}}〜</span>
    </div>
    <br>
    <div class="buttonsBox">
    <div class="buttonContent">
    <span class="buttonsLabel"><a href="/teacher/class/{{thisclass.id}}/task/create/">宿題を追加</a></span>
    </div>
        <div class="buttonContent">
        <span class="buttonsLabel"><a href="./tasks">宿題一覧</a></span>
        </div>
        <div class="buttonContent">
        <span class="buttonsLabel"><a href="./tags/">タグを管理</a></span>
        </div>
    </div>
    <h3>タグごとの問題の正解率</h3>
    <div style="margin-top: 20px;"></div>
    <div class="tagsbox">
    {%for tag in tags%}
    <div>{{tag.tag.tag}}</div>
    <span id='tag{{tag.tag.id}}'></span>　
    <div class="graph"><div class="graphleft" id="graph{{tag.tag.id}}"></div></div>
    <br>
    {%endfor%}
    </div>
    <div style="margin-top: 20px;"></div>

    {%if sts%}
    <div style="margin-top: 20px;"></div>
    <h3>生徒一覧</h3>
    <br>
    {%for st in sts%}
    <div class="listbox">
        <div class="formboxtitle"><li><a href="./st/{{st.id}}/">{{st.name}}</a></li></div>
    </div>
    {%endfor%}
    {%else%}
    <h4>参加している生徒はいません</h4>
    {%endif%}
    <div style="margin:50px;"></div>

</div>
<script>
    function effect(id,t,f) { 
	    var element = document.getElementById('graph'+id);
        console.log('tag'+id);
        let t2 = Math.floor(t / (t+f)*100);  
	    element.style.width = t2+'%'; 
        console.log(t2+'%');
        document.getElementById('tag'+id).textContent = '合計;'+(t+f)+' 正解:'+t+'('+t2+'%) 不正解:'+f+'('+(100-t2)+'%)';
	}
    let t = 0;
    let f = 0;
    let id = 0;
    {%for tag in tags%}
    t = {{tag.true}};
    f = {{tag.false}};
    id = {{tag.tag.id}};
    console.log('tag'+id);
    console.log(t,f,id);
    effect(id,t,f);
    {%endfor%}
</script>
    {% endblock content %}

team1app/teachers/templates/teachers/CreateClass.html
{% extends 'base_teacher.html' %}

{% load static %}
{% block css %} 
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/class_teacher.css' %}">
{% endblock css %}




{% block title %}
<title>Document</title>
{% endblock title %}




{% block content %}
    <div class = "container">
        <div class ="Contentstitle">
            <span>クラス作成</span>
        </div>
        <br style="margin: 40px;">
        <div class="formoutbox">
            <div class="forminbox">
        <form action="" method="post">
            {%if result%}
            <span style="width: 600px;"><font color="red">{{result}}</font></span>
            <div style="margin: 20px;"></div>
            {%endif%}
            {% csrf_token %}
            <span>クラス名 : </span>
            <input type="input" name="name" minlength="1" maxlength="32">
            <div style="margin: 20px;"></div>
            <span>クラスのパスワード : </span>
            <input type="input" name="password" minlength="4" maxlength="32"><br>
            <div style="margin: 20px;"></div>
            <button type="submit" >create</button>
        </form>
            </div>
            </div>
    </div>


{% endblock content %}

team1app/teachers/templates/teachers/DistributeTask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

team1app/teachers/templates/teachers/TaskContent.html
{% extends 'base_teacher.html' %}

{% load static %}
{% block css %} 
<link rel="stylesheet" type="text/css" href="{% static 'teacher/class_teacher.css' %}">
{% endblock css %}


{% block title %}
<title>宿題作成</title>
{% endblock title %}

{% block content %}

{%if task%}
<div class ="container">
<div class ="Contentstitle">
<span>宿題詳細</span>
</div>
<div style="margin: 40px;"></div>
<div class="formoutbox">
<div class="forminbox">
<form action="" method="post">
{% csrf_token %}
<input type="hidden" name="type" value="change"/>
<span>宿題</span>
<input type="input" name="name" minlength="1" maxlength="32" value="{{task.name}}">
<div style="margin-top: 20px;"></div>
<span>内容</span>
<textarea name="content" maxlengt="800"　rows="4" cols="60">{{task.contents}}</textarea>
<div style="margin-top: 20px;"></div>
<span>作成日: </span><span>{{task.make}}</span>
<div style="margin: 20px;"></div>
<button type="submit" >change</button>
</form>
</div>
</div>
{%endif%}
<div style="margin: 20px;"></div>
<div class="formoutbox">
<div class="forminbox">
<form action="" method="post">
{% csrf_token %}
<input type="hidden" name="type" value="delete"/>
<span>付けられたタグ</span>
<div class="outbox">
{% for tag in thistags %}
    <div class="inbox">
<input type="checkbox" id="tags{{tag.id}}" name="tags" value="{{tag.id}}">
<label for="tags{{tag.id}}">{{tag.tag}}</label>
</div>
{%endfor%}
</div>
<div style="margin: 20px;"></div>
<button type="submit" >delete</button>
</form>
</div>
</div>

<div style="margin: 40px;"></div>
<div class="formoutbox">
<div class="forminbox">
<form action="" method="post">
{% csrf_token %}
<input type="hidden" name="type" value="addtags"/>
<span>タグ一覧</span>
<div class="outbox">
{%for tag in tags%}
<div class="inbox">
<input type="checkbox" id="tags{{tag.id}}" name="tags" value="{{tag.id}}">
<label for="tags{{tag.id}}">{{tag.tag}}</label>
</div>
{%endfor%}
</div>
<div style="margin: 20px;"></div>
<button type="submit" >add</button>
</form>
<br>
{%if students%}
</div>
</div>

<div style="margin: 40px;"></div>
<div class="formoutbox">
<div class="forminbox">
<form action="" method="post">
<span>宿題を出す</span>
<div style="margin: 20px;"></div>
{% csrf_token %}
<span>期限</span>
<div style="margin: 20px;"></div>
<input type="hidden" name="type" value="students"/>
    <span class="radio-contents"><input class="radios" type="radio" name="days" value="0">1日後</span>
    <span class="radio-contents"><input class="radios" type="radio" name="days" value="1">2日後</span>
    <span class="radio-contents"><input class="radios" type="radio" name="days" value="2">3日後</span>
    <span class="radio-contents"><input class="radios" type="radio" name="days" value="3">4日後</span>
    <span class="radio-contents"><input class="radios" type="radio" name="days" value="4">5日後</span>
    <span class="radio-contents"><input class="radios" type="radio" name="days" value="5">6日後</span>
    <span class="radio-contents"><input class="radios" type="radio" name="days" value="6">1週間後</span>
    <span class="radio-contents"><input class="radios" type="radio" name="days" value="7">2週間後</span>
<span class="radio-contents"><input class="radios" type="radio" name="days" value="8">4週間後</span>
<div style="margin: 20px;"></div>
<span>課題を行う生徒</span>
<div style="margin: 20px;"></div>
<div class="studentsbox">
    <ul>
{% for student in students %}
<li><input type="checkbox" name="students" value ="{{student.id}}"/>{{student.name}}</li>
{%endfor%}
</ul>
</div>
<div style="margin: 20px;"></div>
<button type="submit" >create</button>
</form>
</div>
</div>
<div style="margin: 80px;"></div>
{%endif%}

{% endblock content %}

team1app/teachers/templates/teachers/TaskCreate.html
{% extends 'base_teacher.html' %}

{% load static %}
{% block css %} 
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/class_teacher.css' %}">
{% endblock css %}


{% block title %}
<title>宿題作成</title>
{% endblock title %}




{% block content %}
<div class="backbutton"><a href="../../">クラス詳細へ<br>戻る</a></div>
    <div class ="container">
        <div class ="Contentstitle">
            <span>宿題作成</span>
        </div>
        <hr>
        <div style="margin: 40px;"></div>
        <div class="formoutbox">
            <div class="forminbox">
        <form action="" method="post">
            {%if result%}
            <span style="width: 600px;"><font color="red">{{result}}</font></span>
            <div style="margin: 20px;"></div>
            {%endif%}
            {% csrf_token %}
            <span>宿題</span>
            <input type="input" name="name" minlength="1" maxlength="32">
            <div style="margin: 20px;"></div>
            <span>内容</span>
            <textarea name="content" maxlengt="800"　rows="8" cols="35">ここに内容を書いてください。</textarea>
            <div style="margin: 20px;"></div>
            <button type="submit" >create</button>
        </form>
        </div>
        </div>
    </div>



{% endblock content %}

team1app/teachers/templates/teachers/TaskList.html
{% extends 'base_teacher.html' %}
{% load static %}
{% block css %} 
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/class_teacher.css' %}">
{% endblock css %}



{% block title %}
<title>クラス一覧</title>
{% endblock title %}


{% block content %}
<div class="backbutton"><a href="../">クラス詳細へ<br>戻る</a></div>
<div class ="container">
    <div class ="Contentstitle">
        <span>宿題一覧</span>
    </div> 
    {%if tasks%}
    <div class="listbox">

        <div class="listblock">
            <div>宿題名</div>
            <div style = "color:red;">
            <div>付けられたタグ</div>
            </div>
            <div>作成日時</div>
            </div>

    {%for task in tasks%}
    <div class="listblock">
    <div><a href="../task/{{task.id}}/">{{task.name}}</a></div>
    {%if task.tag.all%}
    <div style = "color:red;">
    {%for tag in task.tag.all %}
    <div>{{tag.tag}}</div>
    {%endfor%}
    </div>
    {%else%}
    <div><div>なし</div></div>
    {%endif%}
    <div>{{task.make}}</div>
    </div>
    {%endfor%}
    </div>
    {%else%}
    <h4>まだ宿題は作成されていません</h4>
    {%endif%}
</div>
    {%endblock content%}

team1app/teachers/templates/teachers/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/base_teacher.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/form_teacher.css' %}">
    {% block css %} 
    
    {% endblock css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'form.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Caveat|Quicksand:400,700" rel="stylesheet">
    {% block title %}  {% endblock title %} 
  </head>
  <body class = "body">  
    
    
    <header>
      <h1 class="headline">
        <a>+NoteBook</a>
      </h1>
      <ul class="nav-list">
        <li class="nav-list-item">
          <a href="{% url 'home' %}" >Home</a>
        </li>
        <li class="nav-list-item"><a  href="{% url 'login' %}" >SignOut</a></li>
        <li class="nav-list-item">Topic</li>
      </ul>

      <p class = "headline" align="right">ユーザー名：{{ user.username }}</p>
    </header>        

   {% block header %}
   {% endblock header %}
   {% block content %}

   {% endblock content %}

    <!-- java html -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

team1app/teachers/templates/teachers/class.html
{% extends 'base_teacher.html' %}
{% load static %}
{% block css %} 
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/class_teacher.css' %}">
{% endblock css %}



{% block title %}
<title>クラス一覧</title>
{% endblock title %}


{% block content %}
    <div class ="container">
        <div class ="Contentstitle">
            <span>クラス一覧</span>
        </div> 
        <hr>
        <div class="buttonsBox">
            <div class="buttonContent">
        <span class="buttonsLabel"><a href="{% url 'teacher:CreateClass'%}">クラス作成</a></span>
        </div>
        <div class="buttonContent">
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="type" value="my">
            <input type="hidden" name="join" value="">
            <label for="myclass" class="buttonsLabel">MyClass</label> 
            <input id="myclass" class="buttonsInput" type="submit" value="MyClass"/>
        </form>
        </div>
        <div class="buttonContent">
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="type" value="all">
            <input type="hidden" name="join" value="">
            <label for="all"class="buttonsLabel" >All</label> 
            <input id="all" class="buttonsInput" type="submit" value="All"/>
        </form>
        </div>
        </div>
        {% if classes %}
        {% if all %}
        <ui>
        {% for class in classes %}
        <form action="" method="post" class="listbox">
            {% csrf_token %}
            <div class="formboxtitle"><li>{{class.class_name}}</li></div>
            <input type="hidden" name="join" value="{{class.id}}">
            <input type="hidden" name="type" value="all">
            <div class="formboxbutton"><input type="submit" value="join"/></div>
        </form>
        {% endfor %}
        </ui>
        {%else%}
        <ul>
        {% for class in classes %}
        <div class="listbox">
            <div class="formboxtitle"><li><a href="/teacher/class/{{class.id}}/">{{class.class_name}}</a></li></div>
        </div>
        {% endfor %}
        </ul>
        {%endif%}
        {%else%}
        <h4 class = "a">クラスはまだありません</h4>
        {%endif%}
        {%if result%}
        <script>
            alert("{{result}}");
        </script>
        {%endif%}
    </div>   
    

{%  endblock content%}

team1app/teachers/templates/teachers/home.html
{% extends 'base_teacher.html' %}

{% load static %}
{% block css %} 
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/class_teacher.css' %}">
{% endblock css %}


{% block title %}
<title>Document</title>
{% endblock title %}


{% block content %}
    <div class ="container">
        <div class ="title">
            <h1>Title</h1>
        </div>
        <hr>
        <h4>Your teacher</h4>
        <h4><a href="{% url 'teacher:teclass'%}">クラス一覧</a></h4>
    </div>

{% endblock content %}

team1app/teachers/templates/teachers/questions.html
{% extends 'base_teacher.html' %}
{% load static %}
{% block css %} 
    <link rel="stylesheet" type="text/css" href="{% static 'teacher/class_teacher.css' %}">
{% endblock css %}



{% block title %}
<title>質問一覧</title>
{% endblock title %}


{% block content %}
<div class ="container">
    <div class ="Contentstitle">
        <span>質問一覧</span>
    </div> 
    <div class="listbox">

        <div class="listblock2">
            <div>質問した生徒</div>
            <div>タイトル</div>
            <div>宿題名</div>
            <div>最終更新日時</div>
            </div>
{%if questions%}
{%for q in questions%}
<div class="listblock2">
<div>FROM. {{q.fromSt.name}}</div>
    <div><a href = "./{{q.id}}">{{q.title}}</a></div>
    <div> {{q.task.name}}</div>
    <div>{{q.finalup}}</div>
</div>
{%endfor%}
</div>
{%else%}
</div>
<div style="width: 100%;text-align: center;">
<h3 style="display: inline;">質問はありません</h3>
</div>
{%endif%}
{%endblock content%}