team1app/blog/urls.py
from rest_framework import routers
#from .views import UserViewSet, EntryViewSet


router = routers.DefaultRouter()


"""
router.register(r'users',UserViewSet)
router.register(r'entries',EntryViewSet)
"""

team1app/students/urls.py
from django.urls import path, re_path
from . import views,test

from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static


# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'students'

urlpatterns = [

    path('', views.home, name = 'home'),
    path('home/<int:class_id>/', views.class_page, name = "class_page"), 
    path('home/task/', views.task, name = 'task'),
    path('home/propose/', views.propose, name = 'propose'),
    path('home/tag/', views.tag, name = 'tag'),

    path('home/chat/<int:id>/', views.room, name = 'room'),
    path('home/chat/', views.chat, name = 'chat'),
    path('home/chat/create/', views.chat_create, name = 'chat_create'),

]

team1app/team1app/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog.urls import router as blog_router
from django.urls import path, include
from teachers.views import home as tehome
from students.views import home as sthome
from blog import web_views_private as priv




urlpatterns=[
    path(r'admin/', admin.site.urls),
    path(r'api/', include(blog_router.urls)),
    #blog
    path('home/',priv.home,name='home'),
    path(r'', include('blog.web_urls')),

    path(r'accounts/',include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('student/',include('students.urls')),
    path('teacher/',include('teachers.urls',namespace="teacher")),
    path('teacher/home/',tehome,name='tehome'),
    path('student/home/',sthome,name='sthome'),
    
]

team1app/students/models.py
from django.db import models

# Create your models here.

team1app/students/views.py
from django.shortcuts import render,redirect
from blog.web_views_private import check
from blog.models import * 
from students.tools import * 
from django.utils import timezone
import datetime

# Create your views here.
def home(request):
    """studentのhome画面"""
    user_student,num = check(request)
    data = {"html":"background-image:url(../../../static/img/math.png)"}
    if num != 2:
        return redirect('home')
    if request.method != 'POST':
        if (user_student.classes_set.all()):
            classes = user_student.classes_set.all()
            data = {"classes":classes,"all":False,"html":"background-image:url(../../../static/img/math.png)"}
            return render(request, 'home.html', data)
        return render(request, 'home.html',data)
    elif request.POST["type"] == "my" :
        if (user_student.classes_set.all()):
            classes = user_student.classes_set.all()
            data = {"classes":classes, "all":False, "html":"background-image:url../../../static/img/math.png)"}
            return render(request,'home.html', data)
        return render(request, 'home.html',data)
    elif request.POST["join"] !="":
        c = Classes.objects.filter(id = int(request.POST["join"]))
        if(c.filter(students = user_student).exists()):
            result = "すでに参加済みのクラスです"
        else:   
            c[0].students.add(user_student)
            c[0].save() 
            result = c[0].class_name + "に参加しました"
        base = Base.objects.get(id = user_student.use_base)
        if (base.classes_set.all()):
            classes=base.classes_set.all()
            data = {"classes":classes,"all":True,"result":result,"html":"background-image:url(../../../static/img/math.png)"}
            return render(request,'home.html',data)    
    else:
        base = Base.objects.get(id = user_student.use_base)
        if (base.classes_set.all()):
            classes=base.classes_set.all()
            data = {"classes":classes, "all":True}
            return render(request, 'home.html', data)
    return render(request, 'home.html',data)

def class_page(request,class_id):
    """studentのclass_page画面"""
    #生徒以外はリダイレクト
    student,num = check(request)
    if num != 2:
        return redirect('home')
    #ユーザーが使用しているベースにクラスが属しているか確認
    have, thisclass = checkCL(student.use_base, class_id)
    #クラスが属していた
    if have :
            #クラスに生徒がいる場合
            if (thisclass.students.all()!= None):
                if(student.studenttasks_set.all().exists()):
                    tasks=student.studenttasks_set.all()
                    tasks2=[]
                    for i in tasks:
                        task = gettask(i)
                        if(task.tarclass==thisclass):
                            data={"task":i,"name":task.name,"contents":task.contents}
                            tasks2.append(data)
                    context = {'tasks':tasks2}
                    return render(request, 'class_page.html', context)
                return render(request, 'class_page.html')
            #クラスに生徒がいない場合
            else:
                data= { "thisclass" : thisclass }
                return render(request,'class_page.html',data)
    #クラスに属していない
    else:
        return redirect("/student/home/")
    # クラスに出された宿題を表示する
    if request.method =='POST':
        tasks = Tasks(name = request.POST["name"], contents = request.POST['contents'], tarclass = thisclass)
        tasks.save()
    context = {'tasks':tasks}
    return render(request, 'class_page.html', context)

def task(request):
    """task画面"""
    student,num = check(request)
    if num != 2:
        return redirect('home')
    datas = student.getMyClassHomework()
    data  = {
        'datas' : datas
    }
    return render(request, 'task.html', data)

def propose(request):
    """propose画面"""
    _,num = check(request)
    if num == 2:
        return render(request, 'propose.html')
    else:
        return redirect('home')

def tag(request):
    """tag画面"""
    cnt = 0
    #生徒以外はリダイレクト
    student,num = check(request)
    if num != 2:
        return redirect('home')
    
    if request.method == "POST":
        finish1 = request.POST["userid1"]
        content = finish1.split(":")
        
        for i in range(int(len(content)/3)):
            if content[i] =="":
                break
            task=StudentTasks.objects.get(id = int(content[i * 3]))
            task.finish = True
            if(content[i * 3 + 2] == "true"):
                task.result = True
            task.save()
        
    if(student.studenttasks_set.all().exists()):
        tasks=student.studenttasks_set.all()
        classes = student.classes_set.all()
        tasks2=[]
        for i in tasks:
            task = gettask(i)
            if i.finish ==0:
                cnt +=1
            data={"task":i,"name":task.name,"contents":task.contents}
            tasks2.append(data)
        context = {'tasks':tasks2,'cnt':cnt,"classes":classes}
        return render(request, 'tag.html', context)
    else:
        classes = student.classes_set.all()
        context = {"classes":classes}
        return render(request, 'tag.html',context)
    

def chat(request):
    student,num = check(request)
    if num != 2:
        return redirect('home') 
    if request.method == 'POST':
        teacher = Teachers.objects.get( id = int(request.POST["select_teachers"]))
        task = Tasks.objects.get(id = int(request.POST["select_tasks"]))
        questions = Question.objects.create(title = request.POST['comment'], task = task, toTe = teacher, fromSt = student)
        print(questions)
        questions.save()
    q = student.getQuestions()
    data = {"questions": q }
    return render(request,'chat.html', data)

def chat_create(request):
    student, num = check(request)
    if num != 2:
        return redirect('home')   
    if request.method == 'POST':
        teacher = Teachers.objects.get( id = int(request.POST["select_teachers"]))
        task = Tasks.objects.get(id = int(request.POST["select_tasks"]))
        questions = Question.objects.create(title = request.POST['comment'], task = task, toTe = teacher, fromSt = student)
        print(questions)
        questions.save()
    questions = Question.objects.order_by('-finalup')   
    teacher_name = Teachers.objects.all()
    task_name = Tasks.objects.all()
    context = {
            "teacher" : teacher_name,
            "questions": questions,
            "tasks" : task_name
    }
    return render(request, 'chat_create.html', context)
   
def room(request, id):
    student, num = check(request)
    if num != 2:
        return redirect('home') 
    text = "コメントを入力"
    if request.method == "POST":
        if(request.POST["type"] == "comment"):
            Question.objects.get(id = id).addCommentSt(request.POST["comment"])
        else:
            text = request.POST["comment"]
    context = {
        'Comment' : Question.objects.get(id = id).getComment(),
        'one' :  Question.objects.get(id = id),
        'text': text,
    }
    return render(request, 'room.html', context)

team1app/students/templates/chat.html
<!--質問・予約機能のページ（生徒側）new ver-->
{% extends 'base_student.html' %}
{% block title %}
<title>Document</title>
{% endblock title %}
{% block content %}
    
    
    <div class="chat_p_div">
        <p class="chat_p">トーク一覧</p>
        <p class="chat_p_a"><a href="{% url 'students:chat_create' %}" class="chat_a_btn">質問・予約する</a></p>
    </div>
    
    <ul class="chat_talk_ul">
        {%if questions%}
        {% for q in questions %}
        <a href="./{{q.id}}/" class="chat_a">
        <li class="chat_talk_list">Title:{{ q.title }}
            {{ q.toTe.name }}
            {{ q.task.name }}
            <br>
            <p class="chat_finalup">{{q.finalup}}</p>
        </li>
        </a>
        {% endfor %}
        {%else%}
        <li class="chat_talk_list">質問はありません</li>
        {%endif%}
    </ul>
    

{% endblock content %}

team1app/students/templates/chat_create.html
{% extends 'base_student.html' %}
{% block title %}
<title>Document</title>
{% endblock title %}
{% block content %}

<form action ="/student/home/chat/" method="POST">
<div class="chat_create_div">
    <h3>先生を選択</h3>
    <select name="select_teachers" size = "1">
        {% for t in teacher %}
        <option value="{{t.id}}">{{ t.name }}</option>
        {% endfor %}
    </select>
</div>

<div class="chat_create_div">
    <h3>予約日時</h3>
    <input type = "datetime-local" name = "datetime" value = "">
</div>

<div class="chat_create_div">
    <h3>課題を選択</h3>
    <select name="select_tasks" size = "1">
        {% for task in  tasks %}
        <option value="{{task.id}}">{{ task.name }}</option>
        {% endfor %}
    </select>
</div>

<div class="chat_create_div">
    <h3>質問内容</h3>
        {% csrf_token %}
        <p><textarea class="text" name="comment" value = ""></textarea></p>    
</div>
<input type = "submit" value="送信" class="chat_create_submit">
</form>

 {% endblock content %}

team1app/students/templates/class_page.html
{% extends 'base_student.html' %}

{% block title %}
<title>Document</title>
{% endblock title %}

{% block content %}
    {%if thisclass%}
    <p>クラス名</p>
    <h2>{{thisclass.class_name}}</h2>
    {%endif%}
    <br>
    {% if tasks %}
    {% for task in tasks %}
    <div class="class_page_div">
    <div class="class_page_div2"><p>課題名：{{ task.name }}</p></div>
    <p class="class_page_p">内容：{{ task.contents }}</p>
    <p class="class_page_p">しめきり：{{ task.task.limit }}</p>
    </div>
   

    {% endfor %}
    
    {% else %}
    <div class="class_page_div">
        <div class="class_page_div2">課題名：</div>
    <p class="class_page_p">課題は出されていません。</p>
    </div>
    {% endif %}

    <br>
    <script>
    var data = [{% for task in tasks %}
              ["{{ task.task.limit }}","{{ task.task.isResult }}","{{ task.name }}","{{ task.contents }}"],
              {% endfor %}
             ];

    var a = data[0][0];
    console.log(a);




</script>
      
{% endblock content %}

team1app/students/templates/home.html
<!--HOMEページ（生徒側）-->


{% extends 'base_student.html' %}
{% block title %}
<title>Document</title>
{% endblock title %}


{% block content %}

<head>
 

  <style>


    .swiper-container {
      width: 100%;
      padding-top: 200px;
      padding-bottom: 50px;
    }
    
    .swiper-slide {
      background-position: center;
      background-size: cover;
      width: 200px;
      height: 200px;
      /* Center slide text vertically */
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
      
    }
    .s-fade-text {
  position: absolute;
  top: 20%;
  left: 0;
  width: 100%;
  text-align: center;
  color: white;
  font-size: 5vw;
}
img{
  width: 100%;
  height: 100%;
}
    
    
  </style>
</head>


<body>
 {% if classes %}
 {% if all %}
 {% for class in classes %}
 <form action="" method="post">
     {% csrf_token %}
     <h4>{{class.class_name}}</h4>
     <input type="hidden" name="join" value="{{class.id}}">
     <a href="" ><input type="hidden" name="type" value="all"></a>
     <input type="submit" value="Join"/> 
 </form>
 {% endfor %}
 {%else%}
 <div class="swiper-container">
    <div class="swiper-wrapper">
 {% for class in classes %}
<div class="swiper-slide">
<a href ="{{class.id}}">
{% if class.class_name == "数学"  or class.class_name == "math" or class.class_name == "国語" or class.class_name == "nation" or class.class_name == "理科" or class.class_name == "science" or class.class_name == "社会" or class.class_name == "society" %}
<img   src="../../../static/img/{{class.class_name}}.png" id = "{{class.id}}">
{% else %}
<img   src="../../../static/img/noImage.png" id = "{{class.id}}">
{% endif %}
</a>
</div>

 <!-- <h1><a href="/student/home/{{class.id}}">{{class.class_name}}</a></h1> -->
 {% endfor %}

 </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
  </div>
 {%endif%}
 {%else%}
 <h4>クラスはまだありません</h4>
 {%endif%}
 {%if result%}
 {%endif%}
 
  <table>
    <tr>
        <td>
          <form action="" method="post">
              {% csrf_token %}
              <input type="hidden" name="type" value="my">
              <input type="hidden" name="join" value=""> 
              <input class="simpleButton" type="submit" value="My_Class">
          </form>
        </td>
        <td>
          <form action="" method="post">
              {% csrf_token %}
              <input type="hidden" name="type" value="all">
              <input type="hidden" name="join" value="">
              <input class="simpleButton" type="submit" value="All"/>
          </form>
        </td>
    </tr>

 </table>


</body>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<script>
  var swiper = new Swiper('.swiper-container', {
    effect: 'coverflow',
    grabCursor: true,
    loop: true,
    autoplay: {
      delay: 5000,
      disableOnInteraction: false,
    },
    centeredSlides: true,
    slidesPerView: 'auto',
    coverflowEffect: {
      rotate: 50,
      stretch: 0,
      depth: 100,
      modifier: 1,
      slideShadows: true,
    },
    pagination: {
      el: '.swiper-pagination',
    },
  });
  var data = [{% for class in classes %}
              "{{ class.class_name }}",
              {% endfor %}
             ];
  for (let i = 0; i < data.length; i++){
    
    if(data[i]=="数学"){
      var img0 = document.getElementById("0");
      console.log(data[i]);
      //img0.style = "background-image:url(../../../static/img/math.png)";
    }
    else if(data[i] =="理科"){
      var img1 = document.getElementById("1");
      img1.src = "science.png";
    }
    else if(data[i] =="社会"){
      var img2 = document.getElementById("2");
      img2.src = "society.png";
    }
    else{
      var img3 = document.getElementById("3");
      img3.src = "nation.png";

    }
  }
  function effect(){
    var img0 = document.getElementById("sample2");
      console.log(data[0]);
      img0.style ="background-image:url(../../../static/img/math.png)";

  }

</script>

</html>
{% endblock content %}

team1app/students/templates/propose.html
<!--反復・自動提案機能のページ（生徒側）-->


{% extends 'base_student.html' %}



{% block title %}
<title>Document</title>
{% endblock title %}



{% block content %}

<head>
 

  <style>

    .swiper-container {
      width: 100%;
      padding-top: 200px;
      padding-bottom: 50px;
    }
    .swiper-slide {
      background-position: center;
      background-size: cover;
      width: 200px;
      height: 200px;
    }
    
  </style>
</head>

<body>
  <!-- Swiper -->
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <div class="swiper-slide" style="background-image:url(../../../static/img/ICON/math.jpg)"></div>
      <div class="swiper-slide" style="background-image:url(../../../static/img/ICON/sience.png)"></div>
      <div class="swiper-slide" style="background-image:url(../../../static/img/ICON/1-01.png)"></div>
      <div class="swiper-slide" style="background-image:url(../../../static/img/ICON/1-01.png)"></div>

    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
  </div>
  <table>
    <tr>
        <td>
          <form action="" method="post">
              {% csrf_token %}
              <input type="hidden" name="type" value="my">
              <input type="hidden" name="join" value=""> 
              <input class="btn btn--orange btn--radius" type="submit" value="My_Class"/>
          </form>
        </td>
        <td>
          <form action="" method="post">
              {% csrf_token %}
              <input type="hidden" name="type" value="all">
              <input type="hidden" name="join" value="">
              <input class="btn btn--orange btn--radius" type="submit" value="All"/>
          </form>
        </td>
    </tr>

 </table>
 {% if classes %}
 {% if all %}
 {% for class in classes %}
 <form action="" method="post">
     {% csrf_token %}
     <h4>{{class.class_name}}</h4>
     <input type="hidden" name="join" value="{{class.id}}">
     <a href="" ><input type="hidden" name="type" value="all"></a>
     <input type="submit" value="Join"/> 
 </form>
 {% endfor %}
 {%else%}
 {% for class in classes %}
 <h1><a href="/student/home/{{class.id}}">{{class.class_name}}</a></h1>
 {% endfor %}
 {%endif%}
 {%else%}
 <h4>クラスはまだありません</h4>
 {%endif%}
 {%if result%}
 {%endif%}



</body>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<script>
  var swiper = new Swiper('.swiper-container', {
    effect: 'coverflow',
    grabCursor: true,
    loop: true,
    autoplay: {
      delay: 2000,
      disableOnInteraction: false,
    },
    centeredSlides: true,
    slidesPerView: 'auto',
    coverflowEffect: {
      rotate: 50,
      stretch: 0,
      depth: 100,
      modifier: 1,
      slideShadows: true,
    },
    pagination: {
      el: '.swiper-pagination',
    },
  });
</script>

</html>

    

{% endblock content %}

team1app/students/templates/room.html
{% extends 'base_student.html' %}
{% block title %}
<title>Document</title>
{% endblock title %}
{% block content %}
<h1 class="room_h1">{{ one.toTe.name }} </h1>

{%for c in Comment%}
<div class="room_talk">
{%if c.isStudent%}
    <div class = "comment right">
      <!--   student_name:{{one.fromSt.name}}
      <br>  -->
    <p>{{c.comment}}</p>
    <br>
    </div>
    
{%else%}
    <div class = "comment left">
      <!--  teacher_name:{{ one.toTe.name }} 
      <br>
      -->
      <p>{{c.comment}}</p>
      <br>
    </div>

{%endif%}
</div>
{%endfor%}



<br>
<form name = "form1"  action="" method="post" class="commentbox" >
    {% csrf_token %}
    <input type = "hidden" name="type" value="comment">
    <textarea name = "comment" minlength="1" rows="5" cols="40" autofocus></textarea>
    <br>
    <input type="submit" value="send"/>
</form>

<script>
    document.form1.comment.value = "{{text}}";
    var c = document.form1.comment.value;
    var n = function(){
      document.form1.type.value = "text";
      document.form1.submit();
    } 
    setInterval(n, 15000);
  </script>

{% endblock content %}

team1app/students/templates/tag copy.html
<!--タグ機能のページ（生徒側）-->
{% extends 'base_student.html' %}



{% block title %}
<title>Document</title>
{% endblock title %}



{% block content %}
<style>


    .swiper-container {
      width: auto;
      position: center;
      
    }
    .swiper-slide {
      background-position: center;
      background-size: cover;
      
      
    }
    
table{
  width: 100%;
  border-spacing: 0;
}

table th{
  border-bottom: solid 2px #fb5144;
  padding: 10px 0;
}

table td{
  border-bottom: solid 2px #ddd;
  text-align: center;
  padding: 10px 0;
}
.col-1 {
    display: inline-block;
    width: 200px;
    /* border: solid 1px; */
}
.col-2 {
    display: inline-block;
    width: 100px;
    /* border: solid 1px; */
}
   


    
  </style>


    <h1> Tag page / タグ機能</h1>




    <table>
    
  <tr>
    <th>課題４</th>
    <td>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide" style="background-color: #EDF7FF;">Not</div>
                    <div class="swiper-slide"><a href="{% url 'students:reserve' %}">Reserve</a></div>
            
                </div>
	        </div>
        </td>
  </tr>
  <tr>
    <th>課題３</th>
    <td>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide" style="background-color: #EDF7FF;">Not</div>
                    <div class="swiper-slide">Not</div>
            
                </div>
	        </div>
        </td>
  </tr>
  <tr>
    <th>課題２</th>
    <td>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide" style="background-color: #EDF7FF;">Not</div>
                    <div class="swiper-slide">Not</div>
            
                </div>
	        </div>
        </td>
  </tr>
  <tr>
    <th>課題１</th>
        <td>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide" style="background-color: #EDF7FF;">Not</div>
                    <div class="swiper-slide">Not</div>
            
                </div>
	        </div>
        </td>
  </tr>
</table>
  
    
    <input type="button" value="Exec" onclick="OnButtonClick();"/><br />

    <p><a href="{% url 'students:task' %}">Task</a></p>
    <p><a href="{% url 'students:propose' %}">Propose</a></p>
    <p><a href="{% url 'students:reserve' %}">Reserve</a></p>
    <p><a href="{% url 'students:chat' %}">Chat</a></p>
    
    <br>
    <p><a href="{% url 'students:home' %}">home</a></p>

    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

	<!-- Initialize Swiper -->
	<script>
		var mySwiper = new Swiper('.swiper-container');
        console.log(mySwiper.realIndex);
        function OnButtonClick() {
            console.log(mySwiper.realIndex);}

	</script>

  <script>


  </script>

{% endblock content %}

team1app/students/templates/task.html
<!--宿題機能のページ（生徒側）-->
{% extends 'base_student.html' %}
{% block title %}
<title>Document</title>
{% endblock title %}

{% block content %}
<div class = "task_body">
    <h1>課題一覧</h1>
    {% if datas %}
    {%  for data in datas %}
    <h3 class="task_h3">クラス：{{data.class.class_name }}</h3>
    {% for homework in data.homeworks %}
    {% for task in homework.task.all%}
    <div>
    <p class="task_p"><a onclick="alert('課題名：{{task.name}}\n内容：{{task.contents}}\n{% if homework.finish %}解答済み{% else %}未解答{%endif%}\n期限：{{homework.limit}}\nタグ名：{% for tag in task.tag.all%} {{tag.tag}} {%endfor%}\n')" href="" class="task_a_btn">{{ task.name}}</a>
       <br> {{ homework.limit}}</p>
        {%endfor%}
   
    </div>
    {%endfor%}
    {%endfor%}
    {%endif%}

    <p><a href="{% url 'home' %}" class="btn_home">戻る</a></p>
</div>
{% endblock content %}